galaxy_info:
  author: Edleson Duarte
  description: 
  company: Pontoclass Consultoria e Treinamento
  license: MIT
  min_ansible_version: 1.2
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
  galaxy_tags: []
dependencies: []
  