---
# tasks file for webmin
- name: Add webmin repo 
  apt_repository: repo='deb http://download.webmin.com/download/repository sarge contrib' update_cache=yes
  become: yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  
- name:  Add webmin mirror repo 
  apt_repository: repo='deb http://webmin.mirror.somersettechsolutions.co.uk/repository sarge contrib' update_cache=yes
  become: yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    
- name: Addkey webmin
  apt_key: url=http://www.webmin.com/jcameron-key.asc  state=present
  become: yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Atualizando a distribuição do linux
  apt:
    update_cache: yes
    dpkg_options: 'force-confold,force-confdef'
  become: yes

- name: Instalando o webmin
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ ansible_webmin_packages }}"
  become: yes

